name: unaltraweb-template

services:
  jekyll:
    container_name: unaltraweb-template-jekyll
    image: amirpourmand/al-folio:v0.16.1
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
