name: Deploy site

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: dosquartsdedocs/unaltraweb/.github/workflows/site-deploy.yml@396e2b646757f37f941c864b0c96d20bdf4f7dde
    with:
      install-python-requirements: false
      check-computations: true
